// Generated by CoffeeScript 1.6.3
(function() {
  var fs, http, mime, path, router, server;

  http = require('http');

  fs = require('fs');

  path = require('path');

  mime = require('mime');

  router = require('./router.js');

  console.log(router);

  server = http.createServer(function(req, res) {
    return router.route(req, res);
  });

  server.listen(8080);

}).call(this);
