// Generated by CoffeeScript 1.6.3
(function() {
  var fs, http, mime, path, server;

  http = require('http');

  fs = require('fs');

  path = require('path');

  mime = require('mime');

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello World\n');
  });

  server.listen(8080);

}).call(this);
